//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.24 at 02:10:24 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://erp.integration.spring.poc.shawnyang.com/order", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.shawnyang.poc.spring.integration.erp.order;
