//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:22:59 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://integration.spring.poc.shawnyang.com/erp", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.shawnyang.poc.spring.integration.erp;
